image: python:2

variables:
  DOCKER_DRIVER: overlay2

before_script:
    - pip install --upgrade pip-tools
    - pip-compile --output-file requirements/dev.txt requirements/dev.in
    - pip install -r requirements/dev.txt

stages:
    - lint
    - unit_test
    - function_test

lint_job:
    stage: lint
    script:
        - flake8 lettuce_rest

unit_test_job:
    stage: unit_test
    script:
        - py.test

function_test_job:
    stage: function_test
    script:
        - cd tests
        - lettuce
